[platformio]
default_envs = cardputer

[env:cardputer]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
upload_protocol = esp-builtin
upload_speed = 115200
build_flags =
  -DESP32S3
  -DMCU_ESP32
  -DBOARD_CARDPUTER_ADV
  -DCORE_DEBUG_LEVEL=5
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DUSTORE_USE_UNIVERSALFS
  -DMSGPACK_USE_BOOST=OFF
lib_deps =
  https://github.com/attermann/Crypto.git
  https://github.com/attermann/microStore.git
  https://github.com/attermann/microReticulum.git
  https://github.com/konsumer/arduino-rns-password.git
  m5stack/M5Cardputer
