// monochrome dark

#define THEME_FG WHITE
#define THEME_BG BLACK
#define THEME_TAB_FG LIGHTGREY
#define THEME_TAB_BG BLACK
#define THEME_TAB_ACTIVE_FG BLACK
#define THEME_TAB_ACTIVE_BG DARKGREY
#define THEME_BATTERY_BG BLACK
#define THEME_BATTERY_FG DARKGREY