// monochrome dark

#define THEME_FG WHITE
#define THEME_BG BLACK
#define THEME_TAB_FG LIGHTGREY
#define THEME_TAB_BG BLACK
#define THEME_TAB_ACTIVE_FG BLACK
#define THEME_TAB_ACTIVE_BG DARKGREY
#define THEME_BATTERY_BG BLACK
#define THEME_BATTERY_FG DARKGREY
#define THEME_SCROLL THEME_TAB_FG
#define THEME_SELECTED_FG BLACK
#define THEME_SELECTED_BG RED

#define HEIGHT_HEADER 16
#define HEIGHT_FOOTER 16
